{% set name = "flake8-deprecated" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_deprecated-{{ version }}.tar.gz
  sha256: ee96ca001d1ca0561fa8e46f23e2d2460b18a86696373cab644e102ae0ff2aa2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - flake8

test:
  imports:
    - flake8_deprecated
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Warns about deprecated method calls
  home: https://github.com/gforcada/flake8-deprecated
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
