{% set name = "flake8-deprecated" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gforcada/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2cc9c9da5aad69c65a83b0005d887703f4a2e8d9ec7327c0c5d9b7258988caa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
    - setuptools
  run:
    - python >=3.6
    - flake8

test:
  imports:
    - flake8_deprecated
  commands:
    - pip check
  requires:
    - pip
    - python 3.6

about:
  summary: Warns about deprecated method calls
  home: https://github.com/gforcada/flake8-deprecated
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
