{% set name = "flake8-deprecated" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_deprecated-{{ version }}.tar.gz
  sha256: 84cdb63f735ba976d41b263eac6cbee65bfab211f8748725d4e9dd95017dd1a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - flake8

test:
  imports:
    - flake8_deprecated
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Warns about deprecated method calls
  home: https://github.com/gforcada/flake8-deprecated
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
